### ISSUE TITLE
schedule times in list view

### ISSUE THREAD

**Issue by nicholasdeleo** [martin-rohwedder/MySQL-Backup-Manager#24]
Another great feature would be to be able to see (ideally even edit) the schedule time in the list view.
I have to go back and forth from each database to check the times because there is no way to see all of them together.
Some more information like last backup, last backup size etc. would also be nice as well as multiple criteria to sort the list.

Best,
Nicholas

**Comment by cbaerike** [comment]
Have a look at version 1.4.1: https://github.com/cbaerike/MySQL-Backup-Manager/releases
