### ISSUE TITLE
Manage more than one server

### ISSUE THREAD

**Issue by taisoftsa** [martin-rohwedder/MySQL-Backup-Manager#29]
It would be great if the dumps were created in a folder with the server´s host so we could have more than one server's databases scheduled. If two different servers have databases with the same name it may overwrite them

**Comment by cbaerike** [comment]
Fixed in version 1.4.1: https://github.com/cbaerike/MySQL-Backup-Manager/releases

**Comment by taisoftsa** [comment]
Thanks! Great work!
A few bugs though:
- When clicking to edit a database with the same name on a server it 
opens the first that encounters even if on different server.
- Sometimes when editing it duplicates the database.
Not a bug, but it will be helpful if an alias could be added to the 
server for easiest recognition.

Had to say i'm very pleased with the software

firmajuli Julián Arón
jma@taisoft.com.ar <mailto:jma@taisoft.com.ar>


5218-9977/4345-6121
www.taisoft.com.ar <http://www.taisoft.com.ar/>
El 06/03/2015 a las 10:59 p.m., cbaerike escribió:
>
> Fixed in version 1.4.1: 
> https://github.com/cbaerike/MySQL-Backup-Manager/releases
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/martin-rohwedder/MySQL-Backup-Manager/issues/29#issuecomment-77667183>.
>



---
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
http://www.avast.com

**Comment by cbaerike** [comment]
Thanks for testing! I should have this fixed in version 1.4.2.

**Comment by cbaerike** [comment]
All fixed in 1.4.2: https://github.com/cbaerike/MySQL-Backup-Manager/releases
