### ISSUE TITLE
Install Error 101

### ISSUE THREAD

**Issue by mwsasser** [martin-rohwedder/MySQL-Backup-Manager#32]
After trying to install on windows 7 x64, I get error 101.  The install rolls back and uninstalls.

**Comment by adityasatrio** [comment]
hei I got same error, trying to install it to windows 7 x64, but the error code is 1001

![error 1001](https://cloud.githubusercontent.com/assets/4746146/8372072/ba9ccb08-1c09-11e5-9784-3c25565df4a8.png)
