### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by sranjane** [martin-rohwedder/MySQL-Backup-Manager#35]
Hello Sir,

How to install martin-rohwedder-MySQL-Backup-Manager-v.1.3.1.0-1-g676197e

Please guide me how to install.

Thanks,
sachin

**Comment by cbaerike** [comment]
Please download the latest installer from https://github.com/cbaerike/MySQL-Backup-Manager/releases/latest

**Comment by sranjane** [comment]
Hello ,

Thanks to share our MySQL-Backup-Manager installer,

please close this request

Thanks,
Sachin
