### ISSUE TITLE
Install Error 1001

### ISSUE THREAD

**Issue by JoshuaKissoon** [martin-rohwedder/MySQL-Backup-Manager#38]
I'm running Windows 8.1 64-bit and receive a "Error 1001" error when installing the application. I downloaded MySQLBackupManagerInstaller-v1.3.1.exe from Sourceforge. 

When I press "Ok" on the error popup, it rolls back the installation and allows me to view a log. I've attached a copy of the log file.

![screenshot 2016-01-21 09 48 33](https://cloud.githubusercontent.com/assets/1193750/12482118/416913f8-c024-11e5-9e28-d4a558f2ef5d.png)

[MSI91365.LOG.txt](https://github.com/martin-rohwedder/MySQL-Backup-Manager/files/99197/MSI91365.LOG.txt)

**Comment by cbaerike** [comment]
This has been discussed at length for almost 2 years in multiple threads now.

Fix: https://github.com/cbaerike/MySQL-Backup-Manager/releases
