### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Freakshows** [martin-rohwedder/MySQL-Backup-Manager#39]
Hi
Love the application, one small thing thoe, it would be really great to have an option to backup a db to a self contained *.sql file. 

kind regards
Freak

**Comment by cbaerike** [comment]
Not sure what you're referring to. The files created are SQL files. Are you asking for a function to customize the file extension?

**Comment by Freakshows** [comment]
Hi
I am used to phpMyAdmin where one can export a self contained *.sql file whitch is easy to import into a db, using a verirty of import/export software.
But as backup software i get that it might not be needed in MySQL-Backup-Manager :)

**Comment by cbaerike** [comment]
Hi,

What is currently preventing you from importing the generated file in the import/export software you're used to? The file contents are pretty much the same as what would be generated by PHPMyAdmin, only the file extension is different.

**Comment by Freakshows** [comment]
Ahh i did not know that, i will give it a try.
